# This is a basic workflow to help you get started with Actions

name: Tatooine

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install cluster configurations
        run: |
          sudo apt update
          sudo apt install -y zsh nfs-kernel-server
          sudo ./install.sh tatooine
      - name: Check exports
        run: |
          sudo exportfs -ra
          output=$(sudo exportfs -ra 2>&1)
          if [[ "$output" = *"Assuming"* ]]; then
            echo "$output" >&1
            echo "No assuming is allowed." >&1
            exit 1
          fi
